//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContosoUniversity.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContosoUniversity.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TRIGGER CreateGPAFromStudentTrigger
        ///ON Student
        ///AFTER INSERT AS
        ///BEGIN
        ///	DECLARE @InsertedStudentID AS int
        ///	SELECT @InsertedStudentID = ID FROM INSERTED
        ///	INSERT INTO GPA
        ///	VALUES
        ///		(@InsertedStudentID, NULL)
        ///END.
        /// </summary>
        internal static string CreateGPAFromStudentTrigger {
            get {
                return ResourceManager.GetString("CreateGPAFromStudentTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE FUNCTION GetGPA (@StudentID int) 
        ///RETURNS float
        ///AS
        ///BEGIN
        ///DECLARE @GPA float
        ///SELECT @GPA = ROUND(SUM (StudentTotal.TotalCredits) / SUM (StudentTotal.Credits), 2)
        ///	FROM (
        ///		SELECT 
        ///			CAST(Credits as float) Credits
        ///			, CAST(SUM(Value * Credits) as float) TotalCredits
        ///		FROM 
        ///			Enrollment e 
        ///			JOIN Course c ON c.CourseID = e.CourseID
        ///			JOIN Grade g  ON e.GradeID = g.GradeID
        ///		WHERE
        ///			e.StudentID = @StudentID AND
        ///			e.GradeID IS NOT NULL
        ///		GROUP BY
        ///			StudentID
        ///			, Value
        ///			, e. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetGPA {
            get {
                return ResourceManager.GetString("GetGPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE UpdateGPA @StudentID int AS
        ///UPDATE GPA
        ///	SET Value = dbo.GetGPA(@StudentID)
        ///FROM GPA
        ///WHERE
        ///	StudentID = @StudentID.
        /// </summary>
        internal static string UpdateGPA {
            get {
                return ResourceManager.GetString("UpdateGPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TRIGGER UpdateGPAFromInsert
        ///ON Enrollment
        ///AFTER INSERT AS
        ///--DECLARE @InsertedGradeID AS int
        ///--SELECT @InsertedGradeID = GradeID FROM INSERTED
        ///--IF @InsertedGradeID IS NOT NULL
        ///	BEGIN
        ///		DECLARE @InsertedStudentID AS int
        ///		SELECT @InsertedStudentID = StudentID FROM INSERTED
        ///		EXEC UpdateGPA @InsertedStudentID
        ///	END.
        /// </summary>
        internal static string UpdateGPAFromInsertTrigger {
            get {
                return ResourceManager.GetString("UpdateGPAFromInsertTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TRIGGER UpdateGPAFromUpdateDelete
        ///ON Enrollment
        ///AFTER UPDATE, DELETE AS
        ///BEGIN
        ///	DECLARE @UpdatedStudentID AS int
        ///	SELECT @UpdatedStudentID = StudentID FROM DELETED
        ///	EXEC UpdateGPA @UpdatedStudentID
        ///END.
        /// </summary>
        internal static string UpdateGPAFromUpdateDeleteTrigger {
            get {
                return ResourceManager.GetString("UpdateGPAFromUpdateDeleteTrigger", resourceCulture);
            }
        }
    }
}
